#!/bin/bash
sudo bash -c "ufw allow OpenSSH && ufw enable && ufw status"
sudo bash -c "apt-get update && apt-get upgrade && apt-get install vim sudo curl git golang-go build-essentials"

read -p "Would you like to setup SSH now? [y/N]" STATUS

if [ ${STATUS} = "y" ]; then
        ./linux-ssh-setup
fi

sudo reboot